version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
      time: '08:10'
      timezone: Europe/Istanbul
    groups:
      github-actions:
        patterns:
          - '*'
    open-pull-requests-limit: 5

